language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20
addons:
  postgresql: 9.5
cache:
  directories:
    - _build
    - deps
services:
  - redis-server
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
env:
  - MIX_ENV=test
before_script:
  - bash .travis/postgre_setup.sh
script:
  - mix ecto.create
  - mix ecto.migrate
  - mix coveralls.travis
